In [6]:
import pandas as pd

# Load the dataset
df = pd.read_csv('SupplyChainEmissionFactorsforUSIndustriesCommodities(2016_Summary_Commodity).csv')

# Display the first few rows
df.head()

,Commodity Code,Commodity Name,Substance,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Unnamed: 7,DQ ReliabilityScore of Factors without Margins,DQ TemporalCorrelation of Factors without Margins,DQ GeographicalCorrelation of Factors without Margins,DQ TechnologicalCorrelation of Factors without Margins,DQ DataCollection of Factors without Margins
0,111CA,Farms,carbon dioxide,"kg/2018 USD, purchaser price",0.467,0.046,0.513,NaN,4,2,1,4,1
1,111CA,Farms,methane,"kg/2018 USD, purchaser price",0.025,0.000,0.026,NaN,3,2,1,1,1
2,111CA,Farms,nitrous oxide,"kg/2018 USD, purchaser price",0.002,0.000,0.002,NaN,4,2,1,4,1
3,111CA,Farms,other GHGs,"kg CO2e/2018 USD, purchaser price",0.004,0.000,0.004,NaN,4,2,1,4,1
4,113FF,"Forestry, fishing, and related activities",carbon dioxide,"kg/2018 USD, purchaser price",0.199,0.024,0.223,NaN,4,2,1,4,1

In [7]:
# Check column names and data types
df.info()

# Check for null values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 13 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Commodity Code                                          264 non-null    object
 1   Commodity Name                                          264 non-null    object
 2   Substance                                               264 non-null    object
 3   Unit                                                    264 non-null    object
 4   Supply Chain Emission Factors without Margins           264 non-null    float64
 5   Margins of Supply Chain Emission Factors                264 non-null    float64
 6   Supply Chain Emission Factors with Margins              264 non-null    float64
 7   Unnamed: 7                                              0 non-null      float64
 8   DQ ReliabilityScore of Factors without Margins          264 non-null    int64
 9   DQ TemporalCorrelation of Factors without Margins       264 non-null    int64
 10  DQ GeographicalCorrelation of Factors without Margins   264 non-null    int64
 11  DQ TechnologicalCorrelation of Factors without Margins  264 non-null    int64
 12  DQ DataCollection of Factors without Margins            264 non-null    int64
dtypes: float64(4), int64(5), object(4)
memory usage: 26.9+ KB

Commodity Code                                              0
Commodity Name                                              0
Substance                                                   0
Unit                                                        0
Supply Chain Emission Factors without Margins               0
Margins of Supply Chain Emission Factors                    0
Supply Chain Emission Factors with Margins                  0
Unnamed: 7                                                264
DQ ReliabilityScore of Factors without Margins              0
DQ TemporalCorrelation of Factors without Margins           0
DQ GeographicalCorrelation of Factors without Margins       0
DQ TechnologicalCorrelation of Factors without Margins      0
DQ DataCollection of Factors without Margins                0
dtype: int64

In [8]:
import numpy as np

# Select numeric columns
numeric_cols = df.select_dtypes(include=[np.number]).columns

# Function to remove outliers using IQR
def remove_outliers_iqr(data, columns):
    for col in columns:
        Q1 = data[col].quantile(0.25)
        Q3 = data[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        # Keep only rows within bounds
        data = data[(data[col] >= lower_bound) & (data[col] <= upper_bound)]
    return data

# Remove outliers
df_cleaned = remove_outliers_iqr(df, numeric_cols)

# Compare original and cleaned dataset
print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", df_cleaned.shape)

Original dataset shape: (264, 13)
Cleaned dataset shape: (0, 13)

In [9]:
# Save to a new CSV
df_cleaned.to_csv('cleaned_dataset.csv', index=False)